require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reading_times", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ReadingTime. As you add validations to ReadingTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReadingTime.create! valid_attributes
      get reading_times_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reading_time = ReadingTime.create! valid_attributes
      get reading_time_url(reading_time)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reading_time_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      reading_time = ReadingTime.create! valid_attributes
      get edit_reading_time_url(reading_time)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReadingTime" do
        expect {
          post reading_times_url, params: { reading_time: valid_attributes }
        }.to change(ReadingTime, :count).by(1)
      end

      it "redirects to the created reading_time" do
        post reading_times_url, params: { reading_time: valid_attributes }
        expect(response).to redirect_to(reading_time_url(ReadingTime.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReadingTime" do
        expect {
          post reading_times_url, params: { reading_time: invalid_attributes }
        }.to change(ReadingTime, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post reading_times_url, params: { reading_time: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reading_time" do
        reading_time = ReadingTime.create! valid_attributes
        patch reading_time_url(reading_time), params: { reading_time: new_attributes }
        reading_time.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reading_time" do
        reading_time = ReadingTime.create! valid_attributes
        patch reading_time_url(reading_time), params: { reading_time: new_attributes }
        reading_time.reload
        expect(response).to redirect_to(reading_time_url(reading_time))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        reading_time = ReadingTime.create! valid_attributes
        patch reading_time_url(reading_time), params: { reading_time: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reading_time" do
      reading_time = ReadingTime.create! valid_attributes
      expect {
        delete reading_time_url(reading_time)
      }.to change(ReadingTime, :count).by(-1)
    end

    it "redirects to the reading_times list" do
      reading_time = ReadingTime.create! valid_attributes
      delete reading_time_url(reading_time)
      expect(response).to redirect_to(reading_times_url)
    end
  end
end
