# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_groups", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserGroup. As you add validations to UserGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserGroup.create! valid_attributes
      get user_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_group = UserGroup.create! valid_attributes
      get user_group_url(user_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_group = UserGroup.create! valid_attributes
      get edit_user_group_url(user_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserGroup" do
        expect {
          post user_groups_url, params: { user_group: valid_attributes }
        }.to change(UserGroup, :count).by(1)
      end

      it "redirects to the created user_group" do
        post user_groups_url, params: { user_group: valid_attributes }
        expect(response).to redirect_to(user_group_url(UserGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserGroup" do
        expect {
          post user_groups_url, params: { user_group: invalid_attributes }
        }.to change(UserGroup, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_groups_url, params: { user_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_group" do
        user_group = UserGroup.create! valid_attributes
        patch user_group_url(user_group), params: { user_group: new_attributes }
        user_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_group" do
        user_group = UserGroup.create! valid_attributes
        patch user_group_url(user_group), params: { user_group: new_attributes }
        user_group.reload
        expect(response).to redirect_to(user_group_url(user_group))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_group = UserGroup.create! valid_attributes
        patch user_group_url(user_group), params: { user_group: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_group" do
      user_group = UserGroup.create! valid_attributes
      expect {
        delete user_group_url(user_group)
      }.to change(UserGroup, :count).by(-1)
    end

    it "redirects to the user_groups list" do
      user_group = UserGroup.create! valid_attributes
      delete user_group_url(user_group)
      expect(response).to redirect_to(user_groups_url)
    end
  end
end
